# Generated by Django 5.0.6 on 2024-08-02 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_items_rename_email_students_matric_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_paid',
            name='user',
        ),
        migrations.AddField(
            model_name='items_paid',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.students'),
            preserve_default=False,
        ),
    ]
