# Generated by Django 5.0.6 on 2024-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_remove_items_paid_user_items_paid_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='student',
            field=models.ManyToManyField(related_name='studentPay', to='Admin.students'),
        ),
    ]
