# Generated by Django 5.0.6 on 2024-08-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_items_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_paid',
            name='status',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
