# Generated by Django 5.0.6 on 2024-08-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_items_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='account_balance',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
